FROM jenkins/jenkins:lts

# RUN /usr/local/bin/install-plugins.sh
ENV JENKINS_OPTS --httpPort=8090

USER root

# Install various tools & JRE
RUN apt-get clean && \
  apt-get update && \
  apt-get -qy install \
    wget \
    openjdk-8-jdk \
    telnet \
    iputils-ping \
    unzip \
    maven

# Install jmeter
RUN mkdir /jmeter \
  && cd /jmeter/ \
  && wget http://apache.mirror.iphh.net//jmeter/binaries/apache-jmeter-3.3.tgz \
  && tar -xzf apache-jmeter-3.3.tgz \
  && rm apache-jmeter-3.3.tgz \
  && cd apache-jmeter-3.3/lib/ext \
  && wget https://github.com/NovaTecConsulting/JMeter-InfluxDB-Writer/releases/download/v-1.2/JMeter-InfluxDB-Writer-plugin-1.2.jar \
  && chown -R jenkins:jenkins /jmeter \
  && cd /

# Install InspectIT Agent
RUN mkdir /inspectIT \
  && cd /inspectIT \
  && wget https://github.com/inspectIT/inspectIT/releases/download/1.8.5.101/inspectit-agent-java6-1.8.5.101.zip \
  && unzip inspectit-agent-java6-1.8.5.101.zip \
  && chown -R jenkins:jenkins /inspectIT \
  && cd /

USER jenkins

# Set Jmeter Home
ENV JMETER_HOME /jmeter/apache-jmeter-3.3/

# Add Jmeter to the Path
ENV PATH $JMETER_HOME/bin:$PATH

COPY jenkins_plugins.txt /usr/share/jenkins/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/plugins.txt
